name = "mind-map"
pages_build_output_dir = "dist"
compatibility_date = "2026-06-25"

[[d1_databases]]
binding = "DB"
database_name = "mind-map-db"
database_id = "49ddfb1b-a6ba-4317-a66c-062ba0d3b83f"
